spring.application.name=swmo
server.port=9099
spring.datasource.url=jdbc:postgresql://hayabusa.proxy.rlwy.net:43767/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=ETtFmhiGpHpcRgmGbzACEhuWTgqxhPtI
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak-production-5d0e.up.railway.app/realms/swmo
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
